// Generated by gencpp from file qcontrol_defs/AttControl.msg
// DO NOT EDIT!


#ifndef QCONTROL_DEFS_MESSAGE_ATTCONTROL_H
#define QCONTROL_DEFS_MESSAGE_ATTCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qcontrol_defs
{
template <class ContainerAllocator>
struct AttControl_
{
  typedef AttControl_<ContainerAllocator> Type;

  AttControl_()
    : thrust(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  AttControl_(const ContainerAllocator& _alloc)
    : thrust(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _thrust_type;
  _thrust_type thrust;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;




  typedef boost::shared_ptr< ::qcontrol_defs::AttControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qcontrol_defs::AttControl_<ContainerAllocator> const> ConstPtr;

}; // struct AttControl_

typedef ::qcontrol_defs::AttControl_<std::allocator<void> > AttControl;

typedef boost::shared_ptr< ::qcontrol_defs::AttControl > AttControlPtr;
typedef boost::shared_ptr< ::qcontrol_defs::AttControl const> AttControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qcontrol_defs::AttControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qcontrol_defs::AttControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qcontrol_defs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'qcontrol_defs': ['/home/kasun/catkin_ws/src/PX4_ROS_packages/qcontrol_defs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qcontrol_defs::AttControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qcontrol_defs::AttControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qcontrol_defs::AttControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qcontrol_defs::AttControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qcontrol_defs::AttControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qcontrol_defs::AttControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qcontrol_defs::AttControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a86e32e294f019a20a1fc67767552aa8";
  }

  static const char* value(const ::qcontrol_defs::AttControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa86e32e294f019a2ULL;
  static const uint64_t static_value2 = 0x0a1fc67767552aa8ULL;
};

template<class ContainerAllocator>
struct DataType< ::qcontrol_defs::AttControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qcontrol_defs/AttControl";
  }

  static const char* value(const ::qcontrol_defs::AttControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qcontrol_defs::AttControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 thrust\n\
\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
";
  }

  static const char* value(const ::qcontrol_defs::AttControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qcontrol_defs::AttControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.thrust);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qcontrol_defs::AttControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qcontrol_defs::AttControl_<ContainerAllocator>& v)
  {
    s << indent << "thrust: ";
    Printer<double>::stream(s, indent + "  ", v.thrust);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QCONTROL_DEFS_MESSAGE_ATTCONTROL_H
