// Generated by gencpp from file qcontrol_defs/CommandAction.msg
// DO NOT EDIT!


#ifndef QCONTROL_DEFS_MESSAGE_COMMANDACTION_H
#define QCONTROL_DEFS_MESSAGE_COMMANDACTION_H

#include <ros/service_traits.h>


#include <qcontrol_defs/CommandActionRequest.h>
#include <qcontrol_defs/CommandActionResponse.h>


namespace qcontrol_defs
{

struct CommandAction
{

typedef CommandActionRequest Request;
typedef CommandActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandAction
} // namespace qcontrol_defs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qcontrol_defs::CommandAction > {
  static const char* value()
  {
    return "1d87843bc14c424b23359395bac95872";
  }

  static const char* value(const ::qcontrol_defs::CommandAction&) { return value(); }
};

template<>
struct DataType< ::qcontrol_defs::CommandAction > {
  static const char* value()
  {
    return "qcontrol_defs/CommandAction";
  }

  static const char* value(const ::qcontrol_defs::CommandAction&) { return value(); }
};


// service_traits::MD5Sum< ::qcontrol_defs::CommandActionRequest> should match 
// service_traits::MD5Sum< ::qcontrol_defs::CommandAction > 
template<>
struct MD5Sum< ::qcontrol_defs::CommandActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qcontrol_defs::CommandAction >::value();
  }
  static const char* value(const ::qcontrol_defs::CommandActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qcontrol_defs::CommandActionRequest> should match 
// service_traits::DataType< ::qcontrol_defs::CommandAction > 
template<>
struct DataType< ::qcontrol_defs::CommandActionRequest>
{
  static const char* value()
  {
    return DataType< ::qcontrol_defs::CommandAction >::value();
  }
  static const char* value(const ::qcontrol_defs::CommandActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qcontrol_defs::CommandActionResponse> should match 
// service_traits::MD5Sum< ::qcontrol_defs::CommandAction > 
template<>
struct MD5Sum< ::qcontrol_defs::CommandActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qcontrol_defs::CommandAction >::value();
  }
  static const char* value(const ::qcontrol_defs::CommandActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qcontrol_defs::CommandActionResponse> should match 
// service_traits::DataType< ::qcontrol_defs::CommandAction > 
template<>
struct DataType< ::qcontrol_defs::CommandActionResponse>
{
  static const char* value()
  {
    return DataType< ::qcontrol_defs::CommandAction >::value();
  }
  static const char* value(const ::qcontrol_defs::CommandActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QCONTROL_DEFS_MESSAGE_COMMANDACTION_H
