// Generated by gencpp from file qcontrol_defs/PathPlan.msg
// DO NOT EDIT!


#ifndef QCONTROL_DEFS_MESSAGE_PATHPLAN_H
#define QCONTROL_DEFS_MESSAGE_PATHPLAN_H

#include <ros/service_traits.h>


#include <qcontrol_defs/PathPlanRequest.h>
#include <qcontrol_defs/PathPlanResponse.h>


namespace qcontrol_defs
{

struct PathPlan
{

typedef PathPlanRequest Request;
typedef PathPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathPlan
} // namespace qcontrol_defs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qcontrol_defs::PathPlan > {
  static const char* value()
  {
    return "cf49295d8e9d40310a490e9a26c5cd75";
  }

  static const char* value(const ::qcontrol_defs::PathPlan&) { return value(); }
};

template<>
struct DataType< ::qcontrol_defs::PathPlan > {
  static const char* value()
  {
    return "qcontrol_defs/PathPlan";
  }

  static const char* value(const ::qcontrol_defs::PathPlan&) { return value(); }
};


// service_traits::MD5Sum< ::qcontrol_defs::PathPlanRequest> should match 
// service_traits::MD5Sum< ::qcontrol_defs::PathPlan > 
template<>
struct MD5Sum< ::qcontrol_defs::PathPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qcontrol_defs::PathPlan >::value();
  }
  static const char* value(const ::qcontrol_defs::PathPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qcontrol_defs::PathPlanRequest> should match 
// service_traits::DataType< ::qcontrol_defs::PathPlan > 
template<>
struct DataType< ::qcontrol_defs::PathPlanRequest>
{
  static const char* value()
  {
    return DataType< ::qcontrol_defs::PathPlan >::value();
  }
  static const char* value(const ::qcontrol_defs::PathPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qcontrol_defs::PathPlanResponse> should match 
// service_traits::MD5Sum< ::qcontrol_defs::PathPlan > 
template<>
struct MD5Sum< ::qcontrol_defs::PathPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qcontrol_defs::PathPlan >::value();
  }
  static const char* value(const ::qcontrol_defs::PathPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qcontrol_defs::PathPlanResponse> should match 
// service_traits::DataType< ::qcontrol_defs::PathPlan > 
template<>
struct DataType< ::qcontrol_defs::PathPlanResponse>
{
  static const char* value()
  {
    return DataType< ::qcontrol_defs::PathPlan >::value();
  }
  static const char* value(const ::qcontrol_defs::PathPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QCONTROL_DEFS_MESSAGE_PATHPLAN_H
