// Generated by gencpp from file qcontrol_defs/PathPlanResponse.msg
// DO NOT EDIT!


#ifndef QCONTROL_DEFS_MESSAGE_PATHPLANRESPONSE_H
#define QCONTROL_DEFS_MESSAGE_PATHPLANRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <qcontrol_defs/Trajectory.h>

namespace qcontrol_defs
{
template <class ContainerAllocator>
struct PathPlanResponse_
{
  typedef PathPlanResponse_<ContainerAllocator> Type;

  PathPlanResponse_()
    : traj()  {
    }
  PathPlanResponse_(const ContainerAllocator& _alloc)
    : traj(_alloc)  {
  (void)_alloc;
    }



   typedef  ::qcontrol_defs::Trajectory_<ContainerAllocator>  _traj_type;
  _traj_type traj;




  typedef boost::shared_ptr< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PathPlanResponse_

typedef ::qcontrol_defs::PathPlanResponse_<std::allocator<void> > PathPlanResponse;

typedef boost::shared_ptr< ::qcontrol_defs::PathPlanResponse > PathPlanResponsePtr;
typedef boost::shared_ptr< ::qcontrol_defs::PathPlanResponse const> PathPlanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qcontrol_defs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'qcontrol_defs': ['/home/kasun/catkin_ws/src/PX4_ROS_packages/qcontrol_defs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49a9b609fb35b3fb4f1de98885cd90e5";
  }

  static const char* value(const ::qcontrol_defs::PathPlanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49a9b609fb35b3fbULL;
  static const uint64_t static_value2 = 0x4f1de98885cd90e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qcontrol_defs/PathPlanResponse";
  }

  static const char* value(const ::qcontrol_defs::PathPlanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Trajectory traj\n\
\n\
================================================================================\n\
MSG: qcontrol_defs/Trajectory\n\
PVA[] pva\n\
uint32[] wait_freq\n\
================================================================================\n\
MSG: qcontrol_defs/PVA\n\
bool is_body_frame\n\
geometry_msgs/Point pos\n\
geometry_msgs/Vector3 vel\n\
geometry_msgs/Vector3 acc\n\
float64 yaw\n\
float64 yaw_rate\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::qcontrol_defs::PathPlanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathPlanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qcontrol_defs::PathPlanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qcontrol_defs::PathPlanResponse_<ContainerAllocator>& v)
  {
    s << indent << "traj: ";
    s << std::endl;
    Printer< ::qcontrol_defs::Trajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.traj);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QCONTROL_DEFS_MESSAGE_PATHPLANRESPONSE_H
