// Generated by gencpp from file qcontrol_defs/SimplePathPlan.msg
// DO NOT EDIT!


#ifndef QCONTROL_DEFS_MESSAGE_SIMPLEPATHPLAN_H
#define QCONTROL_DEFS_MESSAGE_SIMPLEPATHPLAN_H

#include <ros/service_traits.h>


#include <qcontrol_defs/SimplePathPlanRequest.h>
#include <qcontrol_defs/SimplePathPlanResponse.h>


namespace qcontrol_defs
{

struct SimplePathPlan
{

typedef SimplePathPlanRequest Request;
typedef SimplePathPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SimplePathPlan
} // namespace qcontrol_defs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qcontrol_defs::SimplePathPlan > {
  static const char* value()
  {
    return "a912cafb64a9cff88ad0817089dd3cf0";
  }

  static const char* value(const ::qcontrol_defs::SimplePathPlan&) { return value(); }
};

template<>
struct DataType< ::qcontrol_defs::SimplePathPlan > {
  static const char* value()
  {
    return "qcontrol_defs/SimplePathPlan";
  }

  static const char* value(const ::qcontrol_defs::SimplePathPlan&) { return value(); }
};


// service_traits::MD5Sum< ::qcontrol_defs::SimplePathPlanRequest> should match 
// service_traits::MD5Sum< ::qcontrol_defs::SimplePathPlan > 
template<>
struct MD5Sum< ::qcontrol_defs::SimplePathPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qcontrol_defs::SimplePathPlan >::value();
  }
  static const char* value(const ::qcontrol_defs::SimplePathPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qcontrol_defs::SimplePathPlanRequest> should match 
// service_traits::DataType< ::qcontrol_defs::SimplePathPlan > 
template<>
struct DataType< ::qcontrol_defs::SimplePathPlanRequest>
{
  static const char* value()
  {
    return DataType< ::qcontrol_defs::SimplePathPlan >::value();
  }
  static const char* value(const ::qcontrol_defs::SimplePathPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qcontrol_defs::SimplePathPlanResponse> should match 
// service_traits::MD5Sum< ::qcontrol_defs::SimplePathPlan > 
template<>
struct MD5Sum< ::qcontrol_defs::SimplePathPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qcontrol_defs::SimplePathPlan >::value();
  }
  static const char* value(const ::qcontrol_defs::SimplePathPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qcontrol_defs::SimplePathPlanResponse> should match 
// service_traits::DataType< ::qcontrol_defs::SimplePathPlan > 
template<>
struct DataType< ::qcontrol_defs::SimplePathPlanResponse>
{
  static const char* value()
  {
    return DataType< ::qcontrol_defs::SimplePathPlan >::value();
  }
  static const char* value(const ::qcontrol_defs::SimplePathPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QCONTROL_DEFS_MESSAGE_SIMPLEPATHPLAN_H
