// Generated by gencpp from file qcontrol_defs/updatePx4param.msg
// DO NOT EDIT!


#ifndef QCONTROL_DEFS_MESSAGE_UPDATEPX4PARAM_H
#define QCONTROL_DEFS_MESSAGE_UPDATEPX4PARAM_H

#include <ros/service_traits.h>


#include <qcontrol_defs/updatePx4paramRequest.h>
#include <qcontrol_defs/updatePx4paramResponse.h>


namespace qcontrol_defs
{

struct updatePx4param
{

typedef updatePx4paramRequest Request;
typedef updatePx4paramResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct updatePx4param
} // namespace qcontrol_defs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qcontrol_defs::updatePx4param > {
  static const char* value()
  {
    return "7d7333ae7553c5a384a7760af7ff3132";
  }

  static const char* value(const ::qcontrol_defs::updatePx4param&) { return value(); }
};

template<>
struct DataType< ::qcontrol_defs::updatePx4param > {
  static const char* value()
  {
    return "qcontrol_defs/updatePx4param";
  }

  static const char* value(const ::qcontrol_defs::updatePx4param&) { return value(); }
};


// service_traits::MD5Sum< ::qcontrol_defs::updatePx4paramRequest> should match 
// service_traits::MD5Sum< ::qcontrol_defs::updatePx4param > 
template<>
struct MD5Sum< ::qcontrol_defs::updatePx4paramRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qcontrol_defs::updatePx4param >::value();
  }
  static const char* value(const ::qcontrol_defs::updatePx4paramRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qcontrol_defs::updatePx4paramRequest> should match 
// service_traits::DataType< ::qcontrol_defs::updatePx4param > 
template<>
struct DataType< ::qcontrol_defs::updatePx4paramRequest>
{
  static const char* value()
  {
    return DataType< ::qcontrol_defs::updatePx4param >::value();
  }
  static const char* value(const ::qcontrol_defs::updatePx4paramRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qcontrol_defs::updatePx4paramResponse> should match 
// service_traits::MD5Sum< ::qcontrol_defs::updatePx4param > 
template<>
struct MD5Sum< ::qcontrol_defs::updatePx4paramResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qcontrol_defs::updatePx4param >::value();
  }
  static const char* value(const ::qcontrol_defs::updatePx4paramResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qcontrol_defs::updatePx4paramResponse> should match 
// service_traits::DataType< ::qcontrol_defs::updatePx4param > 
template<>
struct DataType< ::qcontrol_defs::updatePx4paramResponse>
{
  static const char* value()
  {
    return DataType< ::qcontrol_defs::updatePx4param >::value();
  }
  static const char* value(const ::qcontrol_defs::updatePx4paramResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QCONTROL_DEFS_MESSAGE_UPDATEPX4PARAM_H
