# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from qcontrol_defs/PosControl.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class PosControl(genpy.Message):
  _md5sum = "eed7274a1b8d41fa4c38270fd529df54"
  _type = "qcontrol_defs/PosControl"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool is_body_frame
geometry_msgs/Point pos
float64 yaw

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['is_body_frame','pos','yaw']
  _slot_types = ['bool','geometry_msgs/Point','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       is_body_frame,pos,yaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PosControl, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.is_body_frame is None:
        self.is_body_frame = False
      if self.pos is None:
        self.pos = geometry_msgs.msg.Point()
      if self.yaw is None:
        self.yaw = 0.
    else:
      self.is_body_frame = False
      self.pos = geometry_msgs.msg.Point()
      self.yaw = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B4d().pack(_x.is_body_frame, _x.pos.x, _x.pos.y, _x.pos.z, _x.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pos is None:
        self.pos = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.is_body_frame, _x.pos.x, _x.pos.y, _x.pos.z, _x.yaw,) = _get_struct_B4d().unpack(str[start:end])
      self.is_body_frame = bool(self.is_body_frame)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B4d().pack(_x.is_body_frame, _x.pos.x, _x.pos.y, _x.pos.z, _x.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pos is None:
        self.pos = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.is_body_frame, _x.pos.x, _x.pos.y, _x.pos.z, _x.yaw,) = _get_struct_B4d().unpack(str[start:end])
      self.is_body_frame = bool(self.is_body_frame)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B4d = None
def _get_struct_B4d():
    global _struct_B4d
    if _struct_B4d is None:
        _struct_B4d = struct.Struct("<B4d")
    return _struct_B4d
