; Auto-generated. Do not edit!


(cl:in-package qcontrol_defs-msg)


;//! \htmlinclude WayPoints.msg.html

(cl:defclass <WayPoints> (roslisp-msg-protocol:ros-message)
  ((yaw
    :reader yaw
    :initarg :yaw
    :type (cl:vector qcontrol_defs-msg:ConstraintAxis)
   :initform (cl:make-array 0 :element-type 'qcontrol_defs-msg:ConstraintAxis :initial-element (cl:make-instance 'qcontrol_defs-msg:ConstraintAxis)))
   (x
    :reader x
    :initarg :x
    :type (cl:vector qcontrol_defs-msg:ConstraintAxis)
   :initform (cl:make-array 0 :element-type 'qcontrol_defs-msg:ConstraintAxis :initial-element (cl:make-instance 'qcontrol_defs-msg:ConstraintAxis)))
   (y
    :reader y
    :initarg :y
    :type (cl:vector qcontrol_defs-msg:ConstraintAxis)
   :initform (cl:make-array 0 :element-type 'qcontrol_defs-msg:ConstraintAxis :initial-element (cl:make-instance 'qcontrol_defs-msg:ConstraintAxis)))
   (z
    :reader z
    :initarg :z
    :type (cl:vector qcontrol_defs-msg:ConstraintAxis)
   :initform (cl:make-array 0 :element-type 'qcontrol_defs-msg:ConstraintAxis :initial-element (cl:make-instance 'qcontrol_defs-msg:ConstraintAxis)))
   (t
    :reader t
    :initarg :t
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (corridors
    :reader corridors
    :initarg :corridors
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass WayPoints (<WayPoints>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WayPoints>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WayPoints)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name qcontrol_defs-msg:<WayPoints> is deprecated: use qcontrol_defs-msg:WayPoints instead.")))

(cl:ensure-generic-function 'yaw-val :lambda-list '(m))
(cl:defmethod yaw-val ((m <WayPoints>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader qcontrol_defs-msg:yaw-val is deprecated.  Use qcontrol_defs-msg:yaw instead.")
  (yaw m))

(cl:ensure-generic-function 'x-val :lambda-list '(m))
(cl:defmethod x-val ((m <WayPoints>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader qcontrol_defs-msg:x-val is deprecated.  Use qcontrol_defs-msg:x instead.")
  (x m))

(cl:ensure-generic-function 'y-val :lambda-list '(m))
(cl:defmethod y-val ((m <WayPoints>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader qcontrol_defs-msg:y-val is deprecated.  Use qcontrol_defs-msg:y instead.")
  (y m))

(cl:ensure-generic-function 'z-val :lambda-list '(m))
(cl:defmethod z-val ((m <WayPoints>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader qcontrol_defs-msg:z-val is deprecated.  Use qcontrol_defs-msg:z instead.")
  (z m))

(cl:ensure-generic-function 't-val :lambda-list '(m))
(cl:defmethod t-val ((m <WayPoints>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader qcontrol_defs-msg:t-val is deprecated.  Use qcontrol_defs-msg:t instead.")
  (t m))

(cl:ensure-generic-function 'corridors-val :lambda-list '(m))
(cl:defmethod corridors-val ((m <WayPoints>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader qcontrol_defs-msg:corridors-val is deprecated.  Use qcontrol_defs-msg:corridors instead.")
  (corridors m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WayPoints>) ostream)
  "Serializes a message object of type '<WayPoints>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'yaw))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'yaw))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'x))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'x))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'y))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'y))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'z))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'z))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 't))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 't))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'corridors))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'corridors))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WayPoints>) istream)
  "Deserializes a message object of type '<WayPoints>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'yaw) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'yaw)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'qcontrol_defs-msg:ConstraintAxis))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'x) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'x)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'qcontrol_defs-msg:ConstraintAxis))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'y) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'y)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'qcontrol_defs-msg:ConstraintAxis))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'z) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'z)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'qcontrol_defs-msg:ConstraintAxis))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 't) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 't)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'corridors) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'corridors)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WayPoints>)))
  "Returns string type for a message object of type '<WayPoints>"
  "qcontrol_defs/WayPoints")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WayPoints)))
  "Returns string type for a message object of type 'WayPoints"
  "qcontrol_defs/WayPoints")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WayPoints>)))
  "Returns md5sum for a message object of type '<WayPoints>"
  "762c41a819a42f04927bbc931431e5b6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WayPoints)))
  "Returns md5sum for a message object of type 'WayPoints"
  "762c41a819a42f04927bbc931431e5b6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WayPoints>)))
  "Returns full string definition for message of type '<WayPoints>"
  (cl:format cl:nil "#This message defines the list of constrained points and yaw that should be use to~%#generate the trajectory.~%~%ConstraintAxis[] yaw			#Can be empy if no need of a trajectory for the YAW. ELSE it should have~%								#the same length as time.~%ConstraintAxis[] x				#Should have the same length as time~%ConstraintAxis[] y~%ConstraintAxis[] z~%~%float64[] t						#Can be a list of two if you have just the initial and final time. Optimal segment time will be used instead~%float64[] corridors~%================================================================================~%MSG: qcontrol_defs/ConstraintAxis~%#This message represents a Yaw target and all the constraints that can be applied to~%#this yaw target. Note that you can only go to the first order of derivation for the yaw (yaw rate control)~%~%float64 axis~%ConstraintValue[] constraints~%================================================================================~%MSG: qcontrol_defs/ConstraintValue~%#A constrained Value represents a constraint on x,y,z, yaw derivatives.~%#For example the constraint equality : Vx = 2.0 or Vx <= 2.0 can be write with the following ConstraintValue Object :~%### derive_order = FIRST_ORDER~%### value = 2.0~%### comparison = EQUAL or comparison = INF~%# For yaw we currently support only first order constraint. And second order constraints ~%#for the position. ~%~%uint32 FIRST_ORDER = 1~%uint32 SECOND_ORDER = 2~%uint32 THIRD_ORDER = 3~%~%bool bndl_valid~%bool bndu_valid~%~%uint8 label					#Not have to be used by the user~%uint32 derive_order			#Can be FIRST_ORDER, SECOND_ORDER , THIRD_ORDER~%float64 bndl~%float64 bndu~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WayPoints)))
  "Returns full string definition for message of type 'WayPoints"
  (cl:format cl:nil "#This message defines the list of constrained points and yaw that should be use to~%#generate the trajectory.~%~%ConstraintAxis[] yaw			#Can be empy if no need of a trajectory for the YAW. ELSE it should have~%								#the same length as time.~%ConstraintAxis[] x				#Should have the same length as time~%ConstraintAxis[] y~%ConstraintAxis[] z~%~%float64[] t						#Can be a list of two if you have just the initial and final time. Optimal segment time will be used instead~%float64[] corridors~%================================================================================~%MSG: qcontrol_defs/ConstraintAxis~%#This message represents a Yaw target and all the constraints that can be applied to~%#this yaw target. Note that you can only go to the first order of derivation for the yaw (yaw rate control)~%~%float64 axis~%ConstraintValue[] constraints~%================================================================================~%MSG: qcontrol_defs/ConstraintValue~%#A constrained Value represents a constraint on x,y,z, yaw derivatives.~%#For example the constraint equality : Vx = 2.0 or Vx <= 2.0 can be write with the following ConstraintValue Object :~%### derive_order = FIRST_ORDER~%### value = 2.0~%### comparison = EQUAL or comparison = INF~%# For yaw we currently support only first order constraint. And second order constraints ~%#for the position. ~%~%uint32 FIRST_ORDER = 1~%uint32 SECOND_ORDER = 2~%uint32 THIRD_ORDER = 3~%~%bool bndl_valid~%bool bndu_valid~%~%uint8 label					#Not have to be used by the user~%uint32 derive_order			#Can be FIRST_ORDER, SECOND_ORDER , THIRD_ORDER~%float64 bndl~%float64 bndu~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WayPoints>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'yaw) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'x) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'y) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'z) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 't) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'corridors) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WayPoints>))
  "Converts a ROS message object to a list"
  (cl:list 'WayPoints
    (cl:cons ':yaw (yaw msg))
    (cl:cons ':x (x msg))
    (cl:cons ':y (y msg))
    (cl:cons ':z (z msg))
    (cl:cons ':t (t msg))
    (cl:cons ':corridors (corridors msg))
))
