(cl:in-package qcontrol_defs-srv)
(cl:export '(FREQ-VAL
          FREQ
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          VELX_INIT-VAL
          VELX_INIT
          VELY_INIT-VAL
          VELY_INIT
          VELZ_INIT-VAL
          VELZ_INIT
          ACCX_INIT-VAL
          ACCX_INIT
          ACCY_INIT-VAL
          ACCY_INIT
          ACCZ_INIT-VAL
          ACCZ_INIT
          YAW-VAL
          YAW
          YAW_RATE_INIT-VAL
          YAW_RATE_INIT
          CORRIDORS-VAL
          CORRIDORS
          T-VAL
          T
          TRAJ-VAL
          TRAJ
))